'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import JSZip from 'jszip';
import type { Locale } from '@/config/site';
import { calculateOutputDimensions,cleanBaseName,defaultSettings,formatBytes,outputExtension,uniqueFilename,type ResizeSettings } from '@/lib/image-utils';
import { decodeFile,processBitmap } from '@/lib/process-image';
import { RelativeSlider } from './RelativeSlider';
import { PreviewPane } from './PreviewPane';

type Item={id:string;file:File;preview:string;width:number;height:number;selected:boolean;status:'ready'|'processing'|'done'|'error'|'cancelled';progress:number;error?:string;override?:ResizeSettings;result?:{blob:Blob;url:string;width:number;height:number;quality:number;targetMet:boolean;name:string}};
const MAX_FILES=20,MAX_FILE=50*1024*1024,MAX_TOTAL=300*1024*1024;
const allowed=new Set(['image/jpeg','image/png','image/webp','image/gif','image/bmp','image/heic','image/heif']);
const copy={
 en:{drop:'Drop images here, paste from the clipboard, or choose files',choose:'Choose Images',limits:'Up to 20 images · 50 MB each · 300 MB per session',settings:'Output settings',mode:'Resize mode',exact:'Exact width and height',width:'Width only',height:'Height only',percent:'Percentage',maxLong:'Longest edge maximum',maxWidth:'Width maximum',maxHeight:'Height maximum',mp:'Megapixel maximum',fit:'Fit method',contain:'Contain — keep everything and add padding',cover:'Cover — fill the frame and crop overflow',stretch:'Stretch — exact size with possible distortion',upscale:'Allow enlargement',warning:'Enlarging beyond the original can reduce sharpness.',format:'Output format',quality:'Quality',target:'Target file size or less',autoReduce:'Reduce resolution further when quality alone cannot meet the target',background:'Background',transparent:'Transparent padding',suffix:'Filename suffix',process:'Resize Images',cancel:'Cancel',retry:'Retry failed',downloadAll:'Download all as ZIP',downloadSelected:'Download selected as ZIP',clear:'Clear all',preview:'Preview',original:'Original',output:'Output',estimated:'Estimated output',reduction:'Reduction',individual:'Individual settings',remove:'Remove',moveUp:'Move up',moveDown:'Move down',ready:'Ready',processing:'Processing',done:'Complete',error:'Error',noFiles:'Add at least one supported image.',pngTarget:'PNG is lossless; an exact target size may require WebP, JPEG, or lower resolution.',privacy:'Images are processed in this browser and are not uploaded to our server.',metadata:'Re-encoding can remove EXIF, GPS, capture date, camera information, and some color-profile data.',unsupported:'This file cannot be read in the browser. Convert it to JPG, PNG, or WebP and try again.',memory:'This device may not have enough memory. Process fewer or smaller images.',targetFail:'The requested target could not be reached without going below the minimum output size.',selected:'Selected',widthLabel:'Width',heightLabel:'Height',focalX:'Horizontal focal point',focalY:'Vertical focal point',originalFormat:'Keep original format',unit:'Unit',download:'Download',compressionNote:'Compression depends on file structure and visual complexity. The tool aims for the closest result below the target but cannot guarantee identical bytes for every format.',close:'Close',save:'Save',useGlobal:'Use global settings',targetNotMet:'target not met',unknown:'unknown'},
 ko:{drop:'이미지를 끌어 놓거나 클립보드에서 붙여넣거나 파일을 선택하세요',choose:'이미지 선택',limits:'최대 20장 · 파일당 50MB · 세션 전체 300MB',settings:'출력 설정',mode:'크기 변경 방식',exact:'정확한 가로와 세로',width:'가로만 입력',height:'세로만 입력',percent:'비율 기준',maxLong:'긴 변 최대',maxWidth:'가로 최대',maxHeight:'세로 최대',mp:'메가픽셀 최대',fit:'비율 맞춤 방식',contain:'전체 표시 — 이미지를 모두 보존하고 여백 추가',cover:'영역 채우기 — 프레임을 채우고 넘치는 부분 자르기',stretch:'강제 맞춤 — 정확한 크기로 변형(왜곡 가능)',upscale:'원본보다 크게 확대 허용',warning:'원본보다 큰 크기로 확대하면 선명도가 낮아질 수 있습니다.',format:'출력 형식',quality:'품질',target:'목표 파일 크기 이하',autoReduce:'품질만으로 목표를 맞추기 어려우면 해상도를 추가로 낮추기',background:'배경색',transparent:'투명 여백',suffix:'파일명 접미사',process:'이미지 크기 변경',cancel:'취소',retry:'실패 파일 다시 시도',downloadAll:'전체 ZIP 다운로드',downloadSelected:'선택 파일 ZIP 다운로드',clear:'모두 지우기',preview:'미리보기',original:'원본',output:'결과',estimated:'예상 출력',reduction:'감소율',individual:'개별 설정',remove:'삭제',moveUp:'위로 이동',moveDown:'아래로 이동',ready:'준비',processing:'처리 중',done:'완료',error:'오류',noFiles:'지원되는 이미지를 한 장 이상 추가해 주세요.',pngTarget:'PNG는 무손실 형식이므로 정확한 목표 용량은 WebP·JPEG 변환 또는 해상도 축소가 필요할 수 있습니다.',privacy:'이미지는 이 브라우저 안에서 처리되며 서버로 업로드되지 않습니다.',metadata:'재인코딩 과정에서 EXIF, GPS, 촬영 날짜, 카메라 정보, 일부 색상 프로필이 제거될 수 있습니다.',unsupported:'이 파일은 브라우저에서 읽을 수 없습니다. JPG, PNG 또는 WebP로 변환한 뒤 다시 시도해 주세요.',memory:'현재 기기의 메모리가 부족할 수 있습니다. 한 번에 처리하는 이미지 수를 줄여 주세요.',targetFail:'최소 출력 크기 아래로 줄이지 않고는 목표 용량에 도달하지 못했습니다.',selected:'선택됨',widthLabel:'가로',heightLabel:'세로',focalX:'가로 초점 위치',focalY:'세로 초점 위치',originalFormat:'원본 형식 유지',unit:'단위',download:'다운로드',compressionNote:'이미지 압축 결과는 파일 구조와 시각적 복잡도에 따라 달라집니다. 도구는 목표 이하에 최대한 가깝게 맞추지만 모든 형식에서 정확히 같은 바이트를 보장하지 않습니다.',close:'닫기',save:'저장',useGlobal:'전체 설정 사용',targetNotMet:'목표 미달',unknown:'알 수 없는 형식'},
 ja:{drop:'画像をドロップ、クリップボードから貼り付け、またはファイルを選択',choose:'画像を選択',limits:'最大20枚・1ファイル50MB・合計300MB',settings:'出力設定',mode:'サイズ変更方法',exact:'幅と高さを指定',width:'幅のみ',height:'高さのみ',percent:'パーセント',maxLong:'長辺の最大値',maxWidth:'幅の最大値',maxHeight:'高さの最大値',mp:'最大メガピクセル',fit:'フィット方法',contain:'全体を表示 — 画像をすべて残して余白を追加',cover:'枠を埋める — 枠を満たしてはみ出しを切り抜き',stretch:'強制変形 — 正確な寸法へ合わせる（歪みの可能性）',upscale:'原寸より大きくする',warning:'原寸を超える拡大は鮮明さを下げる場合があります。',format:'出力形式',quality:'品質',target:'目標ファイル容量以下',autoReduce:'品質だけで達成できない場合は解像度も下げる',background:'背景色',transparent:'透明な余白',suffix:'ファイル名の接尾辞',process:'画像をリサイズ',cancel:'キャンセル',retry:'失敗を再試行',downloadAll:'すべてZIPで保存',downloadSelected:'選択分をZIPで保存',clear:'すべて削除',preview:'プレビュー',original:'原本',output:'出力',estimated:'予想出力',reduction:'削減率',individual:'個別設定',remove:'削除',moveUp:'上へ',moveDown:'下へ',ready:'準備完了',processing:'処理中',done:'完了',error:'エラー',noFiles:'対応画像を1枚以上追加してください。',pngTarget:'PNGは可逆形式のため、目標容量にはWebP・JPEG変換や解像度低下が必要な場合があります。',privacy:'画像はこのブラウザ内で処理され、サーバーへアップロードされません。',metadata:'再エンコードでEXIF、GPS、撮影日、カメラ情報、一部カラープロファイルが削除される場合があります。',unsupported:'このファイルをブラウザで読み取れません。JPG、PNG、WebPへ変換して再試行してください。',memory:'端末のメモリが不足している可能性があります。処理枚数を減らしてください。',targetFail:'最小出力寸法を下回らずに目標容量へ到達できませんでした。',selected:'選択済み',widthLabel:'幅',heightLabel:'高さ',focalX:'横方向の焦点',focalY:'縦方向の焦点',originalFormat:'元の形式を維持',unit:'単位',download:'ダウンロード',compressionNote:'圧縮結果はファイル構造と画像の複雑さで変わります。目標以下へ近づけますが、すべての形式で完全に同じバイト数は保証しません。',close:'閉じる',save:'保存',useGlobal:'全体設定を使う',targetNotMet:'目標未達',unknown:'不明な形式'},
 es:{drop:'Arrastra imágenes, pégalas desde el portapapeles o elige archivos',choose:'Elegir imágenes',limits:'Hasta 20 imágenes · 50 MB por archivo · 300 MB por sesión',settings:'Ajustes de salida',mode:'Modo de tamaño',exact:'Ancho y alto exactos',width:'Solo ancho',height:'Solo alto',percent:'Porcentaje',maxLong:'Máximo del lado largo',maxWidth:'Ancho máximo',maxHeight:'Alto máximo',mp:'Máximo de megapíxeles',fit:'Método de encaje',contain:'Contener — conservar todo y añadir margen',cover:'Cubrir — llenar el marco y recortar',stretch:'Estirar — forzar medidas con posible deformación',upscale:'Permitir ampliación',warning:'Ampliar por encima del original puede reducir la nitidez.',format:'Formato de salida',quality:'Calidad',target:'Tamaño objetivo o inferior',autoReduce:'Reducir también la resolución si la calidad no basta',background:'Fondo',transparent:'Margen transparente',suffix:'Sufijo del archivo',process:'Redimensionar imágenes',cancel:'Cancelar',retry:'Reintentar fallidas',downloadAll:'Descargar todo en ZIP',downloadSelected:'Descargar selección en ZIP',clear:'Borrar todo',preview:'Vista previa',original:'Original',output:'Salida',estimated:'Salida estimada',reduction:'Reducción',individual:'Ajustes individuales',remove:'Eliminar',moveUp:'Subir',moveDown:'Bajar',ready:'Lista',processing:'Procesando',done:'Completa',error:'Error',noFiles:'Añade al menos una imagen compatible.',pngTarget:'PNG es sin pérdida; un objetivo exacto puede requerir WebP, JPEG o menor resolución.',privacy:'Las imágenes se procesan en este navegador y no se suben a nuestro servidor.',metadata:'La recodificación puede eliminar EXIF, GPS, fecha, cámara y parte del perfil de color.',unsupported:'El navegador no puede leer este archivo. Conviértelo a JPG, PNG o WebP y prueba de nuevo.',memory:'Puede faltar memoria en el dispositivo. Procesa menos imágenes.',targetFail:'No se alcanzó el objetivo sin bajar de la dimensión mínima.',selected:'Seleccionada',widthLabel:'Ancho',heightLabel:'Alto',focalX:'Punto focal horizontal',focalY:'Punto focal vertical',originalFormat:'Mantener formato original',unit:'Unidad',download:'Descargar',compressionNote:'La compresión depende de la estructura y la complejidad visual. La herramienta intenta acercarse al objetivo por debajo del límite, pero no garantiza el mismo número de bytes en todos los formatos.',close:'Cerrar',save:'Guardar',useGlobal:'Usar ajustes generales',targetNotMet:'objetivo no alcanzado',unknown:'formato desconocido'}
};

function makeId(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;}
function estimate(item:Item,s:ResizeSettings){const d=calculateOutputDimensions(item,s);const ratio=(d.width*d.height)/(item.width*item.height);const factor=s.format==='image/png'?1.05:s.format==='image/webp'?.42:.55;return Math.max(1024,Math.round(item.file.size*ratio*factor*(s.quality/85)));}
async function normalizeFile(file:File):Promise<File>{
  if(!['image/heic','image/heif'].includes(file.type)&&!/\.(heic|heif)$/i.test(file.name))return file;
  const mod=await import('heic2any');const converted=await mod.default({blob:file,toType:'image/jpeg',quality:.94});const blob=Array.isArray(converted)?converted[0]:converted;return new File([blob],`${cleanBaseName(file.name)}.jpg`,{type:'image/jpeg'});
}
function workerProcess(file:File,s:ResizeSettings,id:string,onProgress:(n:number)=>void,workerRef:React.MutableRefObject<Worker|null>){return new Promise<NonNullable<Item['result']>>((resolve,reject)=>{
  const worker=new Worker('/image-worker.js');workerRef.current=worker;worker.onmessage=e=>{if(e.data.id!==id)return;if(e.data.kind==='progress')onProgress(e.data.progress);if(e.data.kind==='error'){worker.terminate();workerRef.current=null;reject(new Error(e.data.error));}if(e.data.kind==='done'){const blob=new Blob([e.data.buffer],{type:e.data.type});worker.terminate();workerRef.current=null;resolve({blob,url:URL.createObjectURL(blob),width:e.data.width,height:e.data.height,quality:e.data.quality,targetMet:e.data.targetMet,name:''});}};worker.onerror=()=>{worker.terminate();workerRef.current=null;reject(new Error('Worker failed'));};file.arrayBuffer().then(buffer=>worker.postMessage({kind:'process',id,buffer,mime:file.type,settings:s},[buffer])).catch(reject);
});}

export function ImageEditor({locale}:{locale:Locale}){
  const c=copy[locale];const [items,setItems]=useState<Item[]>([]);const [settings,setSettings]=useState<ResizeSettings>(defaultSettings);const [storageReady,setStorageReady]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [editing,setEditing]=useState<string|null>(null);const [selectedPreview,setSelectedPreview]=useState<string|null>(null);const inputRef=useRef<HTMLInputElement>(null);const workerRef=useRef<Worker|null>(null);const cancelled=useRef(false);
  useEffect(()=>{queueMicrotask(()=>{try{const raw=localStorage.getItem('exactresize-settings');if(raw)setSettings({...defaultSettings,...JSON.parse(raw)});}catch{}setStorageReady(true)});},[]);
  useEffect(()=>{if(storageReady)localStorage.setItem('exactresize-settings',JSON.stringify(settings));},[settings,storageReady]);
  const itemsRef=useRef<Item[]>([]);
  useEffect(()=>{itemsRef.current=items},[items]);
  useEffect(()=>()=>{itemsRef.current.forEach(i=>{URL.revokeObjectURL(i.preview);if(i.result)URL.revokeObjectURL(i.result.url)});workerRef.current?.terminate();},[]);
  const addFiles=useCallback(async(list:File[])=>{
    setMessage('');const existing=items.reduce((a,x)=>a+x.file.size,0);const available=MAX_FILES-items.length;const chosen=list.slice(0,Math.max(0,available));let running=existing;const added:Item[]=[];
    for(const raw of chosen){if(raw.size>MAX_FILE||running+raw.size>MAX_TOTAL){setMessage(c.limits);continue;}if(!allowed.has(raw.type)&&!/\.(jpe?g|png|webp|gif|bmp|heic|heif)$/i.test(raw.name)){setMessage(c.unsupported);continue;}
      try{const file=await normalizeFile(raw);const bitmap=await decodeFile(file);added.push({id:makeId(),file,preview:URL.createObjectURL(file),width:bitmap.width,height:bitmap.height,selected:true,status:'ready',progress:0});bitmap.close();running+=file.size;}catch{setMessage(c.unsupported);}
    }
    setItems(prev=>[...prev,...added]);if(added[0])setSelectedPreview(added[0].id);
  },[items,c]);
  useEffect(()=>{const paste=(e:ClipboardEvent)=>{const files=[...(e.clipboardData?.files||[])];if(files.length)addFiles(files)};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste);},[addFiles]);
  const updateSettings=(patch:Partial<ResizeSettings>)=>setSettings(s=>({...s,...patch}));
  const updateItem=(id:string,fn:(x:Item)=>Item)=>setItems(prev=>prev.map(x=>x.id===id?fn(x):x));
  const process=async(onlyFailed=false)=>{if(!items.length){setMessage(c.noFiles);return;}setBusy(true);setMessage('');cancelled.current=false;const used=new Set<string>();
    for(const item of items){if(cancelled.current)break;if(onlyFailed&&item.status!=='error')continue;if(!onlyFailed&&!['ready','error','cancelled','done'].includes(item.status))continue;const s=item.override||settings;updateItem(item.id,x=>({...x,status:'processing',progress:1,error:undefined}));
      try{let result:NonNullable<Item['result']>;if(typeof Worker!=='undefined'&&typeof OffscreenCanvas!=='undefined')result=await workerProcess(item.file,s,item.id,n=>updateItem(item.id,x=>({...x,progress:n})),workerRef);else{const bitmap=await decodeFile(item.file);const r=await processBitmap(bitmap,s,n=>updateItem(item.id,x=>({...x,progress:n})),item.file.type);bitmap.close();result={...r,url:URL.createObjectURL(r.blob),name:''};}
        const ext=outputExtension(s.format,item.file.name);result.name=uniqueFilename(`${cleanBaseName(item.file.name)}${s.suffix}.${ext}`,used);if(!result.targetMet)setMessage(c.targetFail);updateItem(item.id,x=>{if(x.result)URL.revokeObjectURL(x.result.url);return{...x,result,status:'done',progress:100}});
      }catch(err){updateItem(item.id,x=>({...x,status:cancelled.current?'cancelled':'error',error:err instanceof Error?err.message:c.memory,progress:0}));}
    }setBusy(false);
  };
  const cancel=()=>{cancelled.current=true;workerRef.current?.terminate();workerRef.current=null;setBusy(false);setItems(prev=>prev.map(x=>x.status==='processing'?{...x,status:'cancelled',progress:0}:x));};
  const download=(item:Item)=>{if(!item.result)return;const a=document.createElement('a');a.href=item.result.url;a.download=item.result.name;a.click();};
  const downloadZip=async(selectedOnly:boolean)=>{const candidates=items.filter(i=>i.result&&(!selectedOnly||i.selected));if(!candidates.length)return;const zip=new JSZip();for(const i of candidates)zip.file(i.result!.name,i.result!.blob);const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='exactresize-images.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const remove=(id:string)=>setItems(prev=>{const x=prev.find(v=>v.id===id);if(x){URL.revokeObjectURL(x.preview);if(x.result)URL.revokeObjectURL(x.result.url)}return prev.filter(v=>v.id!==id)});
  const move=(id:string,delta:number)=>setItems(prev=>{const a=[...prev],i=a.findIndex(x=>x.id===id),j=i+delta;if(i<0||j<0||j>=a.length)return prev;[a[i],a[j]]=[a[j],a[i]];return a});
  const previewItem=items.find(i=>i.id===selectedPreview)||items[0];const editingItem=items.find(i=>i.id===editing);const totalProgress=items.length?Math.round(items.reduce((a,x)=>a+x.progress,0)/items.length):0;
  return <section className="editor" aria-label={c.settings}>
    <div className="dropZone" onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('dragging')}} onDragLeave={e=>e.currentTarget.classList.remove('dragging')} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove('dragging');addFiles([...e.dataTransfer.files])}}>
      <input ref={inputRef} className="srOnly" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/bmp,image/heic,image/heif,.heic,.heif" multiple onChange={e=>addFiles([...(e.target.files||[])])}/>
      <div className="dropIcon" aria-hidden="true">＋</div><strong>{c.drop}</strong><span>{c.limits}</span><button type="button" onClick={()=>inputRef.current?.click()}>{c.choose}</button><small>🔒 {c.privacy}</small>
    </div>
    {message&&<div className="notice errorNotice" role="alert">{message}</div>}
    <div className="editorLayout">
      <aside className="settingsPanel"><details open><summary>{c.settings}</summary><div className="settingsBody">
        <label>{c.mode}<select value={settings.mode} onChange={e=>updateSettings({mode:e.target.value as ResizeSettings['mode']})}><option value="exact">{c.exact}</option><option value="width">{c.width}</option><option value="height">{c.height}</option><option value="percent">{c.percent}</option><option value="max-long">{c.maxLong}</option><option value="max-width">{c.maxWidth}</option><option value="max-height">{c.maxHeight}</option><option value="megapixels">{c.mp}</option></select></label>
        <div className="dimensionGrid">
          {(settings.mode==='exact'||settings.mode==='width')&&<label>{c.widthLabel} <input type="number" min="1" value={settings.width} onChange={e=>updateSettings({width:Number(e.target.value)})}/></label>}
          {(settings.mode==='exact'||settings.mode==='height')&&<label>{c.heightLabel} <input type="number" min="1" value={settings.height} onChange={e=>updateSettings({height:Number(e.target.value)})}/></label>}
          {settings.mode==='percent'&&<label>% <input type="number" min="1" max="500" value={settings.percent} onChange={e=>updateSettings({percent:Number(e.target.value)})}/></label>}
          {settings.mode==='max-long'&&<label>px <input type="number" min="1" value={settings.maxLong} onChange={e=>updateSettings({maxLong:Number(e.target.value)})}/></label>}
          {settings.mode==='max-width'&&<label>px <input type="number" min="1" value={settings.maxWidth} onChange={e=>updateSettings({maxWidth:Number(e.target.value)})}/></label>}
          {settings.mode==='max-height'&&<label>px <input type="number" min="1" value={settings.maxHeight} onChange={e=>updateSettings({maxHeight:Number(e.target.value)})}/></label>}
          {settings.mode==='megapixels'&&<label>MP <input type="number" min="0.1" step="0.1" value={settings.megapixels} onChange={e=>updateSettings({megapixels:Number(e.target.value)})}/></label>}
        </div>
        <label>{c.fit}<select value={settings.fit} onChange={e=>updateSettings({fit:e.target.value as ResizeSettings['fit']})}><option value="contain">{c.contain}</option><option value="cover">{c.cover}</option><option value="stretch">{c.stretch}</option></select></label>
        {settings.fit==='stretch'&&<div className="notice">⚠ {c.warning}</div>}
        {settings.fit==='cover'&&<><label>{c.focalX}<RelativeSlider label={c.focalX} value={settings.focalX} min={0} max={100} onChange={focalX=>updateSettings({focalX})}/></label><label>{c.focalY}<RelativeSlider label={c.focalY} value={settings.focalY} min={0} max={100} onChange={focalY=>updateSettings({focalY})}/></label></>}
        <label className="checkRow"><input type="checkbox" checked={settings.allowUpscale} onChange={e=>updateSettings({allowUpscale:e.target.checked})}/>{c.upscale}</label>{settings.allowUpscale&&<small className="warningText">{c.warning}</small>}
        <label>{c.format}<select value={settings.format} onChange={e=>updateSettings({format:e.target.value as ResizeSettings['format']})}><option value="original">{c.originalFormat}</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></label>
        {(settings.format==='image/jpeg'||settings.format==='image/webp'||settings.format==='original')&&<label>{c.quality}<RelativeSlider label={c.quality} value={settings.quality} min={5} max={100} onChange={quality=>updateSettings({quality})}/></label>}
        <label className="checkRow"><input type="checkbox" checked={settings.targetEnabled} onChange={e=>updateSettings({targetEnabled:e.target.checked})}/>{c.target}</label>
        {settings.targetEnabled&&<><div className="targetRow"><input aria-label={c.target} type="number" min="1" value={settings.targetValue} onChange={e=>updateSettings({targetValue:Number(e.target.value)})}/><select aria-label={c.unit} value={settings.targetUnit} onChange={e=>updateSettings({targetUnit:e.target.value as 'KB'|'MB'})}><option>KB</option><option>MB</option></select></div><div className="presetRow">{[20,50,100,200,500,1024].map(v=><button type="button" className="chip" key={v} onClick={()=>updateSettings({targetValue:v===1024?1:v,targetUnit:v===1024?'MB':'KB'})}>{v===1024?'1MB':`${v}KB`}</button>)}</div><label className="checkRow"><input type="checkbox" checked={settings.autoReduceResolution} onChange={e=>updateSettings({autoReduceResolution:e.target.checked})}/>{c.autoReduce}</label>{settings.format==='image/png'&&<small className="warningText">{c.pngTarget}</small>}</>}
        <div className="colorRow"><label>{c.background}<input type="color" value={settings.background} onChange={e=>updateSettings({background:e.target.value})}/></label><label className="checkRow"><input type="checkbox" checked={settings.transparent} onChange={e=>updateSettings({transparent:e.target.checked})}/>{c.transparent}</label></div>
        <label>{c.suffix}<input type="text" maxLength={30} value={settings.suffix} onChange={e=>updateSettings({suffix:e.target.value.replace(/[\\/:*?"<>|]/g,'-')})}/></label>
      </div></details></aside>
      <div className="editorMain">
        {previewItem&&<div className="comparison"><div><h3>{c.original}</h3><PreviewPane src={previewItem.preview} alt={`${previewItem.file.name} · ${c.original}`}/></div><div><h3>{c.output}</h3>{previewItem.result?<PreviewPane src={previewItem.result.url} alt={`${previewItem.file.name} · ${c.output}`}/>:<div className="previewPlaceholder">{calculateOutputDimensions(previewItem,previewItem.override||settings).width} × {calculateOutputDimensions(previewItem,previewItem.override||settings).height}px</div>}</div></div>}
        {busy&&<div className="overallProgress" aria-live="polite"><span>{totalProgress}%</span><progress max="100" value={totalProgress}/><button type="button" className="secondary" onClick={cancel}>{c.cancel}</button></div>}
        <div className="actionBar"><button type="button" disabled={busy||!items.length} onClick={()=>process(false)}>{c.process}</button><button type="button" className="secondary" disabled={busy||!items.some(i=>i.status==='error')} onClick={()=>process(true)}>{c.retry}</button><button type="button" className="secondary" disabled={!items.some(i=>i.result)} onClick={()=>downloadZip(false)}>{c.downloadAll}</button><button type="button" className="secondary" disabled={!items.some(i=>i.result&&i.selected)} onClick={()=>downloadZip(true)}>{c.downloadSelected}</button><button type="button" className="ghost" disabled={busy||!items.length} onClick={()=>{items.forEach(i=>{URL.revokeObjectURL(i.preview);if(i.result)URL.revokeObjectURL(i.result.url)});setItems([])}}>{c.clear}</button></div>
        <div className="fileList" aria-live="polite">{items.map((item,index)=>{const s=item.override||settings,d=calculateOutputDimensions(item,s),est=estimate(item,s),red=Math.max(0,Math.round((1-est/item.file.size)*100));return <article className={`fileCard status-${item.status}`} key={item.id}>
          <label className="selectBox"><input type="checkbox" checked={item.selected} onChange={e=>updateItem(item.id,x=>({...x,selected:e.target.checked}))}/><span className="srOnly">{c.selected}</span></label>
          <button className="thumbButton" onClick={()=>setSelectedPreview(item.id)} aria-label={`${c.preview}: ${item.file.name}`}><img src={item.preview} alt=""/></button>
          <div className="fileInfo"><strong title={item.file.name}>{item.file.name}</strong><span>{item.file.type||c.unknown} · {item.width}×{item.height} · {formatBytes(item.file.size)}</span><span>{c.estimated}: {d.width}×{d.height} · {s.format.replace('image/','')} · {formatBytes(est)} · {c.reduction} {red}%</span>{item.result&&<span className="successText">{item.result.width}×{item.result.height} · {formatBytes(item.result.blob.size)} · Q{item.result.quality}{!item.result.targetMet?` · ${c.targetNotMet}`:''}</span>}{item.error&&<span className="errorText">{item.error}</span>}{item.status==='processing'&&<progress max="100" value={item.progress}/>}</div>
          <div className="statusBadge">{c[item.status as keyof typeof c]||item.status}</div>
          <div className="fileActions"><button className="iconButton" aria-label={c.moveUp} disabled={index===0} onClick={()=>move(item.id,-1)}>↑</button><button className="iconButton" aria-label={c.moveDown} disabled={index===items.length-1} onClick={()=>move(item.id,1)}>↓</button><button className="secondary smallButton" onClick={()=>setEditing(item.id)}>{c.individual}</button>{item.result&&<button className="secondary smallButton" onClick={()=>download(item)}>{c.download}</button>}<button className="iconButton danger" aria-label={c.remove} onClick={()=>remove(item.id)}>×</button></div>
        </article>})}</div>
      </div>
    </div>
    <div className="privacyNotes"><p>🔒 {c.privacy}</p><p>ⓘ {c.metadata}</p><p>ⓘ {c.compressionNote}</p></div>
    {editingItem&&<IndividualModal item={editingItem} global={settings} locale={locale} onClose={()=>setEditing(null)} onSave={override=>{updateItem(editingItem.id,x=>({...x,override,status:'ready'}));setEditing(null)}}/>}
  </section>;
}

function IndividualModal({item,global,locale,onClose,onSave}:{item:Item;global:ResizeSettings;locale:Locale;onClose:()=>void;onSave:(s:ResizeSettings)=>void}){
  const c=copy[locale];const [s,setS]=useState<ResizeSettings>(item.override||{...global});useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[onClose]);
  return <div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal wideModal" role="dialog" aria-modal="true" aria-labelledby="individual-title"><button className="iconButton modalClose" aria-label={c.close} onClick={onClose}>×</button><h2 id="individual-title">{c.individual}: {item.file.name}</h2><div className="dimensionGrid"><label>{c.widthLabel}<input type="number" min="1" value={s.width} onChange={e=>setS({...s,mode:'exact',width:Number(e.target.value)})}/></label><label>{c.heightLabel}<input type="number" min="1" value={s.height} onChange={e=>setS({...s,mode:'exact',height:Number(e.target.value)})}/></label></div><label>{c.fit}<select value={s.fit} onChange={e=>setS({...s,fit:e.target.value as ResizeSettings['fit']})}><option value="contain">{c.contain}</option><option value="cover">{c.cover}</option><option value="stretch">{c.stretch}</option></select></label><label>{c.format}<select value={s.format} onChange={e=>setS({...s,format:e.target.value as ResizeSettings['format']})}><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option><option value="original">{c.originalFormat}</option></select></label><label>{c.quality}<RelativeSlider label={c.quality} value={s.quality} min={5} max={100} onChange={quality=>setS({...s,quality})}/></label><div className="modalActions"><button onClick={()=>onSave(s)}>{c.save}</button><button className="secondary" onClick={()=>onSave({...global})}>{c.useGlobal}</button><button className="ghost" onClick={onClose}>{c.cancel}</button></div></section></div>;
}
